add logs

diff --git a/.github/workflows/build-ig.yml b/.github/workflows/build-ig.yml
--- a/.github/workflows/build-ig.yml
+++ b/.github/workflows/build-ig.yml
@@ -67,11 +67,15 @@ jobs:
 
       #  Run SUSHI (FSH → FHIR JSON)
       - name: Run SUSHI
-        run: sushi .
+        run: sushi . --log-level debug
 
       #  Run IG Publisher
       - name: Build IG
         run: java -jar input-cache/publisher.jar publisher -ig .
+             if [ ! -d output ]; then
+              echo "IG Publisher did not create output/"
+              exit 1
+             fi
 
       - name: Fix Permissions
         run: |
@@ -81,6 +85,10 @@ jobs:
       # Fail build if QA errors exist 
       - name: Check QA report
         run: |
+          if grep -q "ERROR" output/qa.html; then
+            echo " IG Publisher QA errors found"
+            exit 1
+          fi
           if grep -q "ERROR" output/qa.html; then
             echo " IG Publisher QA errors found"
             exit 1
